### ISSUE TITLE
Unicode not working in tags

### ISSUE THREAD

**Issue by Silthus** [AlonsoAliaga/AlonsoTags#2]
**Describe the bug**
Unicode formatting is not working in tags. e.g.: `\u25d5` should become `◕` but it simply prints `\u25d5`.

**To Reproduce**
1. Create a new tag with a unicode character (can use [this list](https://forum.maestrea.com/threads/minecraft-symbols-emoticons-and-characters.11264/)
2. Reload tags and apply tag

**Expected behavior**
Unicode characters should be properly rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/755327/108277899-6e92df00-717a-11eb-8832-28469424b8e0.png)

**Important (please complete the following information):**
 - Java version: `11`
 - Plugin version: `1.7-BETA-PRO`
 - Server version: `paper-469 1.16.5-R.01`

**Comment by AlonsoAliaga** [comment]
Hello, you should try using the unicode itself as in the premade tags.
As alternative, you can add this to your command line to start your server `-Dfile.encoding="UTF-8"` so it looks similar to `java -Dfile.encoding="UTF-8" -jar spigot.jar` plus your specific values for xms and other params

**Comment by Silthus** [comment]
Thanks for the response. My issue was that I enclosed the tag in single quotes. With double quotes it worked.

**Comment by AlonsoAliaga** [comment]
Good to hear! 👍
