### ISSUE TITLE
Tags to show in menu based on permission

### ISSUE THREAD

**Issue by IsXGeo** [AlonsoAliaga/AlonsoTags#3]
If like it if tags that players do not have permission for do not appear when they open the tags menu.

**Comment by AlonsoAliaga** [comment]
Hello, this option was already suggested before. As stated in those times that feature will not be added. The free version will (probably) receive an update to make the tags have a different head texture when they are locked. The paid version has more chances to receive an update to show unlocked tags only. However thats not just writing some lines, that requires a lot of work to recode the system, hence why it's still on plans and hasn't been accepted yet.

**Comment by AlonsoAliaga** [comment]
**Plugin was updated:**
[Free version](https://alonsoaliaga.com/AlonsoTags): Locked tags has a different texture
[Pro version](https://alonsoaliaga.com/AlonsoTagsPro): You can filter tags to display all tags or only unlocked tags
