### ISSUE TITLE
Gradient colors for the color selector

### ISSUE THREAD

**Issue by LuluxClient** [AlonsoAliaga/AlonsoTags#6]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
You can use MiniMessage in order to add gradient colors in your tag: https://docs.adventure.kyori.net/minimessage#format 
And it can allow more customization
**Describe the solution you'd like**
Simply add gradient colors in the color GUI
**Describe alternatives you've considered**
Use this method: https://docs.adventure.kyori.net/minimessage#format they have everything already
**Additional context**

**Comment by AlonsoAliaga** [comment]
Hello, sorry but Gradients is not in my plans (at least for now)
