### ISSUE TITLE
Removing Tags

### ISSUE THREAD

**Issue by xFreakss** [AlonsoAliaga/AlonsoTags#7]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
I'm using your plugin to allow my players do use certain tags, which are not automaticaly removed when they haven't the permission node  to use the tag.

**Describe the solution you'd like**
A command to allow administrators, or the console, to set tags for players, or remove them.

**Describe alternatives you've considered**
The plugin automaticaly removes the tag when the player don't has the permission node.

**Additional context**
God bless ya

**Comment by AlonsoAliaga** [comment]
Hello, a command to modify player tags won't be added, at least not in next updates.
Plugin SHOULD check player permission on join to ensure the player still have permission for that tag. This doesn't and will NEVER apply for purchased tags. If they purchased a tag, they have the right to keep using it (even if a permission was required for purchasing it).

It's pretty weird that tags are not removed by itself, as mentioned, iirc the system has a check for that.

Join our discord server on https://alonsoaliaga.com/discord to be able to help you faster and easier. I'm not 24/7 (specially these days as its holydays). Make sure you confirm that none of the above explained matches your situation (specially the part of purchasable tags, that wont be changed)

**Comment by triesharder** [comment]
No, it was a tag granted by permission, without purchases, the permission was removed without the player reconecting, so thats may be the cause of the issue, thanks!

**Comment by AlonsoAliaga** [comment]
Yeah, for performance issues permissions are checked on join to prevent them from keep using tags they dont have permission for!
