### ISSUE TITLE
Hex color support not working

### ISSUE THREAD

**Issue by LuluxClient** [AlonsoAliaga/AlonsoTags#8]
**Describe the bug**
Title says it all

**To Reproduce**
1. go in config.yml
2. go to Tag-not-selected;
3. try hex colors
4. check gyazo

**Expected behavior**
Colors should be supported

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://gyazo.com/c8ae7691a57b6a739c0d4c5f8ed6ee45)

**Important (please complete the following information):**
 - Java version: 17
 - Plugin version: ALPHA-2.07
 - Server version This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version

**Additional context**
none

**Comment by AlonsoAliaga** [comment]
Hex usage: &#aabbcc

PD: ALPHA-2.07? my plugin dont have alpha versions

**Comment by LuluxClient** [comment]
Thanks idk why I didn’t try that I was to tired, you can close this

Le sam. 8 janv. 2022 à 00:25, AlonsoAliaga ***@***.***> a
écrit :

**Comment by AlonsoAliaga** [comment]
I'm closing it now. Good night!
