### ISSUE TITLE
Players can take items from gui

### ISSUE THREAD

**Issue by triesharder** [AlonsoAliaga/AlonsoTags#9]
**Describe the bug**
Open TAGs GUI, shift+click on close menu barrier, the menu is closed, but now you got a barrier in your inventory, and you're able to use it.

**To Reproduce**
1. Open GUI
2. Shift Click on 'Close Menu Button'
4. Done

**Expected behavior**
Player shouldn't be able to pickup items from gui.

**Screenshots**
(https://prnt.sc/26cm3kv)

**Important (please complete the following information):**
 - Java version: 17
 - Plugin version: 2.0.7-BETA-PRO
 - Server version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c189d0)

**Additional context**
I'm brazilian, so 10EUR was kinda expensive for me, but was worth it because my players loved the features, they helped me to build a lot of Tags and colors!

**Comment by AlonsoAliaga** [comment]
Make sure you are not in Creative mode. (creative mode works different than survival)
If you are in survival mode, join my discord server [here](https://alonsoaliaga.com/discord) to be able to share full console log on start up in a bin

**Comment by triesharder** [comment]
I'm currently waiting for discord 10 minute verification time, how should i send the console startup log?
